locations:
  - province: "jakarta"
    cities:
      - "jakarta"
  - province: "west-java"
    cities:
      - "bandung"
      - "depok"
      - "bekasi"
      - "bogor"
  - province: "banten"
    cities:
      - "serang"
      - "tangerang"
      - "south-tangerang"
      - "curug"
  - province: "central-java"
    cities:
      - "semarang"
      - "surakarta"
      - "purwokerto"
      - "wonosobo"
  - province: "east-java"
    cities:
      - "surabaya"
      - "malang"
      - "sidoarjo"
      - "jember"
  - province: "yogyakarta"
    cities:
      - "yogyakarta"
      - "sleman"
      - "bantul"
      - "wates"
  - province: "lampung"
    cities:
      - "bandar-lampung"
      - "metro"
      - "kotabumi"
  - province: "south-sumatra"
    cities:
      - "palembang"
      - "indralaya"
      - "prabumulih"
  - province: "bengkulu"
    cities:
      - "bengkulu-city"
      - "mukomuko"
      - "manna"
  - province: "jambi"
    cities:
      - "jambi-city"
      - "muara-bungo"
      - "sungai-penuh"
  - province: "west-sumatra"
    cities:
      - "padang"
      - "bukittinggi"
      - "solok"
  - province: "riau"
    cities:
      - "pekanbaru"
      - "duri"
      - "rengat"
  - province: "north-sumatra"
    cities:
      - "medan"
      - "sibolga"
      - "berastagi"
  - province: "aceh"
    cities:
      - "banda-aceh"
      - "lhokseumawe"
      - "meulaboh"

weather_map:
  "01": "Clear Sky"
  "02": "Few Clouds"
  "03": "Scattered Clouds"
  "04": "Broken Clouds"
  "09": "Shower Rain"
  "10": "Rain"
  "11": "Thunderstorm"
  "13": "Snow"
  "50": "Mist/Fog"
