locations:
  - province: "jakarta"
    cities:
      - "jakarta"
  - province: "west-java"
    cities:
      - "bandung"
      - "depok"
  - province: "banten"
    cities:
      - "tangerang"
  - province: "central-java"
    cities:
      - "semarang"
  - province: "east-java"
    cities:
      - "surabaya"
  - province: "yogyakarta"
    cities:
      - "yogyakarta"
